name: Build image and upload to registry

on:
  push:
    tags: [ v* ]


jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ vars.DOCKER_REGISTRY }}/library/downloader

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Upload the manifest to the server (${{ vars.HOST_IP_FIRSTVDS }})
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ vars.HOST_IP_FIRSTVDS }}
        username: ${{ secrets.SSH_USER_FIRSTVDS }}
        password: ${{ secrets.SSH_PASS_FIRSTVDS }}
        source: ./manifests/
        target: /home/admin/youtube-grabber

    - name: Make kubernetes deploy
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ vars.HOST_IP_FIRSTVDS }}
        username: ${{ secrets.SSH_USER_FIRSTVDS }}
        password: ${{ secrets.SSH_PASS_FIRSTVDS }} # todo: hide paths in variables
        script: |
                cd youtube-grabber
                sudo kubectl apply -f ./manifests/
                rm -r ./manifests    
